

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distrbution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:1019265227983:android:a99e41a935b3cf5dc06bba",
        testers: "developerrawad@gmail.com",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        release_notes: "First fastlane firebase distrbution"
    )
  end
end
